#!/usr/bin/env python3
"""Generate the embedded SLIP-39 wordlist for osk-bip.

Downloads the 1024-word list published with SLIP-0039, checks it, and
writes core/osk-bip/src/wordlists/slip39.rs. The module holds the words as
published, the SHA-256 of the source file bytes (every word followed by a
single "\\n", UTF-8) so a Rust test can rebuild and re-hash them, and the
length of the longest word.

Usage (needs network; the Rust build does not):
    python3 tools/wordlists/gen-slip39.py
Run from the repository root. Python 3 standard library only.
"""

import hashlib
import urllib.request
from pathlib import Path

URL = "https://raw.githubusercontent.com/satoshilabs/slips/master/slip-0039/wordlist.txt"
OUT = Path("core/osk-bip/src/wordlists/slip39.rs")


def main() -> None:
    raw = urllib.request.urlopen(URL, timeout=180).read()
    digest = hashlib.sha256(raw).hexdigest()
    text = raw.decode("utf-8")
    if not text.endswith("\n") or "\r" in text:
        raise SystemExit("unexpected line endings")
    words = text[:-1].split("\n")
    if len(words) != 1024:
        raise SystemExit(f"{len(words)} words, expected 1024")
    if len(set(words)) != 1024:
        raise SystemExit("duplicate words")
    if len(set(w[:4] for w in words)) != 1024:
        raise SystemExit("first four letters are not unique")
    for w in words:
        if not w.isascii() or not w.islower() or not (4 <= len(w) <= 8):
            raise SystemExit(f"malformed word {w!r}")
    if words != sorted(words):
        raise SystemExit("list is not sorted")

    lines = [
        "//! Generated by tools/wordlists/gen-slip39.py — do not edit.",
        f"//! Source: {URL}",
        "",
        "/// SHA-256 (hex) of the source file: every word followed by `\\n`, UTF-8.",
        f'pub const SHA256: &str = "{digest}";',
        "",
        "/// Characters in the longest word, which is what a panel of words",
        "/// is sized for.",
        f"pub const MAX_DISPLAY_CHARS: usize = {max(len(w) for w in words)};",
        "",
        "/// The 1024 words as published. Each is four to eight lowercase",
        "/// ASCII letters and is identified by its first four.",
        "#[rustfmt::skip]",
        "pub static WORDS: [&str; 1024] = [",
    ]
    lines += [f'    "{w}",' for w in words]
    lines += ["];", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"slip39 sha256={digest} words={len(words)}")


if __name__ == "__main__":
    main()
