//! The three EFF diceware wordlists, embedded at build time.
//!
//! A diceware list turns throws of a six-sided die into words. The long
//! list is five dice a word over 7776 words; the two short lists are four
//! dice a word over 1296. Each module is generated by
//! `tools/diceware/gen.py` from the file committed under
//! `tools/vectors/eff/`, whose README records where it came from and what
//! its digest is, and exposes `SHA256`, `DICE` and `WORDS`.
//!
//! `WORDS` is in roll order, so the roll `1 1 1 1 1` is index 0 and
//! `6 6 6 6 6` is the last: a roll is the index written in base six with
//! one added to each digit. Nothing here is a secret — the lists are
//! public — but a passphrase rolled from one is, and the caller holds it.

pub mod large;
pub mod short1;
pub mod short2;

/// Bits a word of the long list carries: log2(7776).
const LARGE_BITS: f32 = 12.924_813;
/// Bits a word of either short list carries: log2(1296).
const SHORT_BITS: f32 = 10.339_85;

/// Which of the three lists.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum List {
    /// 7776 words, five dice a word.
    Large,
    /// 1296 words, four dice a word.
    Short1,
    /// 1296 words, four dice a word, no two within three edits of each
    /// other and each with its own three-letter prefix.
    Short2,
}

impl List {
    /// The three lists, in the order the tool offers them.
    pub const ALL: [List; 3] = [List::Large, List::Short1, List::Short2];

    /// Dice thrown for one word.
    pub fn dice_per_word(self) -> usize {
        match self {
            List::Large => large::DICE,
            List::Short1 => short1::DICE,
            List::Short2 => short2::DICE,
        }
    }

    /// The words, in roll order.
    pub fn words(self) -> &'static [&'static str] {
        match self {
            List::Large => &large::WORDS,
            List::Short1 => &short1::WORDS,
            List::Short2 => &short2::WORDS,
        }
    }

    /// Words in the list.
    pub fn len(self) -> usize {
        self.words().len()
    }

    /// Never: every list has words.
    pub fn is_empty(self) -> bool {
        false
    }

    /// Bits one word of this list carries, which is log2 of its length.
    pub fn bits_per_word(self) -> f32 {
        match self {
            List::Large => LARGE_BITS,
            List::Short1 | List::Short2 => SHORT_BITS,
        }
    }

    /// The bits `words` words of this list carry, rounded down: what the
    /// passphrase is worth as a whole number.
    pub fn bits(self, words: usize) -> u32 {
        (words as f32 * self.bits_per_word()) as u32
    }

    /// The word one throw of the dice names. `rolls` is exactly
    /// [`dice_per_word`](Self::dice_per_word) faces, each `1..=6`, in the
    /// order they were thrown; anything else is `None`.
    pub fn word(self, rolls: &[u8]) -> Option<&'static str> {
        if rolls.len() != self.dice_per_word() {
            return None;
        }
        let mut index = 0usize;
        for &r in rolls {
            if !(1..=6).contains(&r) {
                return None;
            }
            index = index * 6 + usize::from(r - 1);
        }
        self.words().get(index).copied()
    }

    /// Characters in the longest word of this list, which is what a
    /// panel of them is sized for.
    pub fn max_chars(self) -> usize {
        match self {
            List::Large => large::CHARS,
            List::Short1 => short1::CHARS,
            List::Short2 => short2::CHARS,
        }
    }

    /// The digest of the file this list was baked from.
    pub fn sha256(self) -> &'static str {
        match self {
            List::Large => large::SHA256,
            List::Short1 => short1::SHA256,
            List::Short2 => short2::SHA256,
        }
    }
}
