//! The ten official BIP-39 wordlists, embedded at build time.
//!
//! Each language module is generated by `tools/wordlists/gen.py` from the
//! file published in the BIP repository and exposes the same items:
//! `WORDS` (as published), `NFKD` (the form used for seed derivation),
//! `DISPLAY` (the form a reader sees), `SHA256` (hex digest of the source
//! file) and `MAX_NFKD_BYTES`.
//!
//! Every published list is already in NFKD form, so `NFKD` is a reference
//! to `WORDS` in all ten modules. The two names are kept so that callers
//! state which form they mean and so that a future list that is not
//! NFKD-invariant needs no API change.
//!
//! `DISPLAY` is the NFC form. Decomposed is right for derivation and for
//! typing and wrong for reading: the published Japanese list is base kana
//! plus the combining voicing marks U+3099 and U+309A, so `WORDS` holds
//! `か` + U+3099 where a reader expects `が`, and the published Korean
//! list is conjoining jamo U+1100–U+11C2, where a reader expects Hangul
//! syllables. Composing them gives the words as they are written. Four
//! lists — Japanese, Korean, Spanish and French — have a `DISPLAY` table
//! of their own; in the other six the published form is already composed
//! and `DISPLAY` is a reference to `WORDS`.
//!
//! `slip39` is the 1024-word list published with SLIP-0039, which is a
//! different list from any of the ten and is indexed ten bits at a time.
//! Its words are lowercase ASCII, four to eight letters, each identified
//! by its first four.
//!
//! `readings` is generated from the Unicode Han Database and holds every
//! Mandarin reading of every character in the two Chinese lists, which is
//! what the pinyin and 注音 keyboards look words up by.

pub mod chinese_simplified;
pub mod chinese_traditional;
pub mod czech;
pub mod english;
pub mod french;
pub mod italian;
pub mod japanese;
pub mod korean;
pub mod portuguese;
pub mod readings;
pub mod slip39;
pub mod spanish;

/// Number of words in every list.
pub const WORDLIST_LEN: usize = 2048;

const fn max(a: usize, b: usize) -> usize {
    if a > b { a } else { b }
}

/// Byte length of the longest NFKD word across all ten lists.
pub const MAX_NFKD_BYTES: usize = max(
    max(
        max(english::MAX_NFKD_BYTES, japanese::MAX_NFKD_BYTES),
        max(korean::MAX_NFKD_BYTES, spanish::MAX_NFKD_BYTES),
    ),
    max(
        max(
            max(
                chinese_simplified::MAX_NFKD_BYTES,
                chinese_traditional::MAX_NFKD_BYTES,
            ),
            max(french::MAX_NFKD_BYTES, italian::MAX_NFKD_BYTES),
        ),
        max(czech::MAX_NFKD_BYTES, portuguese::MAX_NFKD_BYTES),
    ),
);
