//! Generated by `tools/fontbake` (`just fonts`). Do not edit.
//!
//! One entry per face; see `tools/fontbake/README.md`.

use super::{Face, Family};

/// Every face, one outline file each.
pub static FACES: &[Face] = &[
    Face {
        family: Family::Regular,
        data: include_bytes!("../../assets/regular.outl"),
    },
    Face {
        family: Family::SemiBold,
        data: include_bytes!("../../assets/semibold.outl"),
    },
    Face {
        family: Family::RegularNarrow,
        data: include_bytes!("../../assets/regular-narrow.outl"),
    },
    Face {
        family: Family::SemiBoldNarrow,
        data: include_bytes!("../../assets/semibold-narrow.outl"),
    },
    Face {
        family: Family::Mono,
        data: include_bytes!("../../assets/mono.outl"),
    },
    Face {
        family: Family::Icon,
        data: include_bytes!("../../assets/icon.outl"),
    },
    Face {
        family: Family::Cjk,
        data: include_bytes!("../../assets/cjk.outl"),
    },
];
