#!/usr/bin/env python3
"""Generate the embedded EFF diceware wordlists for osk-bip.

Reads the three lists committed under tools/vectors/eff/ and writes one
Rust module per list to core/osk-bip/src/diceware/. Each module holds:

  SHA256  hex SHA-256 of the source file bytes. The script checks that
          the file is exactly `rolls<TAB>word\\n` per line, in rising
          roll order with no roll missing, so a Rust test can rebuild
          the same bytes from WORDS and re-hash them.
  WORDS   the words in roll order: index i is the roll whose digits are
          i written in base six with 1 added to each digit.

Offline: the lists are in the repository, and `tools/vectors/eff/README.md`
records where they came from and what their digests are.

Usage:
    python3 tools/diceware/gen.py
Run from the repository root. Python 3 standard library only.
"""

import hashlib
import re
from pathlib import Path

SRC_DIR = Path("tools/vectors/eff")
OUT_DIR = Path("core/osk-bip/src/diceware")

LISTS = [
    ("large", "eff_large_wordlist.txt", 5),
    ("short1", "eff_short_wordlist_1.txt", 4),
    ("short2", "eff_short_wordlist_2_0.txt", 4),
]


def rolls_of(index: int, dice: int) -> str:
    """The dice roll at `index`: base six, one added to each digit."""
    out = []
    for _ in range(dice):
        out.append(str(index % 6 + 1))
        index //= 6
    return "".join(reversed(out))


def main() -> None:
    for name, filename, dice in LISTS:
        raw = (SRC_DIR / filename).read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        text = raw.decode("utf-8")
        if not text.endswith("\n"):
            raise SystemExit(f"{filename}: no final newline")
        lines = text[:-1].split("\n")
        if len(lines) != 6**dice:
            raise SystemExit(f"{filename}: {len(lines)} lines, expected {6 ** dice}")
        words = []
        for i, line in enumerate(lines):
            rolls, _, word = line.partition("\t")
            if rolls != rolls_of(i, dice):
                raise SystemExit(f"{filename} line {i + 1}: roll {rolls} out of order")
            if not word or not word.isascii() or not re.fullmatch(r"[a-z]+(-[a-z]+)*", word):
                raise SystemExit(f"{filename} line {i + 1}: {word!r} is not a word")
            words.append(word)
        if len(set(words)) != len(words):
            raise SystemExit(f"{filename}: a word appears twice")

        body = [
            f"//! Generated by tools/diceware/gen.py -- do not edit.",
            f"//! Source: tools/vectors/eff/{filename}",
            "",
            "/// SHA-256 (hex) of the source file: every roll, a tab, its word",
            "/// and `\\n`, UTF-8.",
            f'pub const SHA256: &str = "{digest}";',
            "",
            f"/// Dice thrown for one word of this list.",
            f"pub const DICE: usize = {dice};",
            "",
            "/// Characters in the longest word, which is what a panel of",
            "/// these words is sized for.",
            f"pub const CHARS: usize = {max(len(w) for w in words)};",
            "",
            "/// The words in roll order: index `i` is the roll whose digits are",
            "/// `i` in base six with one added to each digit.",
            "#[rustfmt::skip]",
            f"pub static WORDS: [&str; {len(words)}] = [",
        ]
        body += [f'    "{w}",' for w in words]
        body += ["];", ""]
        (OUT_DIR / f"{name}.rs").write_text("\n".join(body), encoding="utf-8")
        print(f"{name}: {len(words)} words, {digest}")


if __name__ == "__main__":
    main()
